Name = "Soup.CSharp.Compiler"
Language = "C++"
Version = "0.3.0"
Dependencies = [
	"C:/Users/mwasp/source/repos/Soup/Dependencies/Opal/Source/",
	"../../../../Build/Utilities/",
	# "Soup.Build.Utilities@0.3.0",
]

Interface = "Module.cpp"
