Name = "Soup.Test"
Language = "C#"
Version = "0.1.1"
Source = [
	"Tasks/TestBuildTask.cs",
]

[Dependencies]
Runtime = [
	"../../../Contracts/",
	"../../../Utilities/",
	"../../../Opal/",
	# "Opal@0.2.1",
	"../Compiler/Core/",
	# "Soup.Build.Compiler@0.3.0",
	"../Compiler/MSVC/",
	# "Soup.Build.Compiler.MSVC@0.3.0",
]