Name = "SoupCore"
Version = "0.1.0"

Dependencies = [
	"../../Dependencies/LzmaSdk/CPP/Library/",
	# "../../Dependencies/json11/",
	# "../../Dependencies/toml11/",
	"../OpalExtensions/",
	# "../Engine/Definition/",
	"../Engine/Core/",
	"../Engine/Wrapper/",
	"Soup.Engine.Definition@0.1.0",
	"json11@1.0.0",
	"toml11@1.0.0",
]
Defines = [
	# "LOCAL_DEBUG",
]
Public = "Module.cpp"
IncludePaths = [
	"./",
	"Compiler/",
	"Utils/",
]
