Name = "SoupCore"
Version = "0.1.0"

Dependencies = [
  "../../Dependencies/json11/",
  "../../Dependencies/toml11/",
  "../Opal/",
  "../Build/Core/",
]
Extensions = [
  "../Build/TestExtension/"
]

Public = "Module.cpp"
Source = [
  "Build/System/BuildGraphNodeList.cpp",
  "Build/System/Value.cpp",
]
IncludePaths = [
  "./",
  "Compiler/",
  "Utils/",
]

[Test]
Source = [
  "../Core.UnitTests/gen/Main.cpp"
]