Name = "Soup.Cpp.Compiler.Clang"
Language = "C++"
Version = "0.3.0"
Interface = "Module.cpp"

[Dependencies]
Runtime = [
	"../Core/",
	# "Soup.Build.Compiler@0.3.0",
	"../MSVC/",
	# "Soup.Build.Compiler.MSVC@0.3.0",
]