Name = "Soup.Build.Extensions.Utilities"
Language = "C#"
Version = "0.1.0"
Source = [
	"Recipe/PackageReference.cs",
	"SharedOperations.cs",
]

[Dependencies]
Runtime = [
	{ Reference = "Opal@1.0.3" },
	{ Reference = "Soup.Build.Extensions@0.2.0" },
]