Name = "Monitor"
Version = "1.0.0"
Type = "Executable"
Dependencies = [
    "../../../Dependencies/Detours/src/",
    "../../../Dependencies/Opal/Source/",
    "../Shared/",
]
Source = [
    "Main.cpp",
]
