Name = "Monitor.Shared"
Language = "C++"
Version = "1.0.0"
Defines = [
	# "TRACE_DETOUR_SERVER",
]
Interface = "Module.cpp"

[Dependencies]
Runtime = [
	"../../../Dependencies/Detours/src/",
	"Opal@0.2.1",
]