Name = "Monitor.Shared"
Version = "1.0.0"
Dependencies = [
    "../../../Dependencies/Detours/src/",
    "../../../Dependencies/Opal/Source/",
]
Defines = [
    # "TRACE_DETOUR_SERVER",
]
Public = "Module.cpp"
