Name = "Soup.Build.Extensions"
Language = "C#"
Version = "0.1.4"
Source = [
	"IValueExtensions.cs",
	"IValueTableExtensions.cs",
]

[Dependencies]
Runtime = [
	{ Reference = "Soup.Build@0.1.3", ExcludeRuntime = true },
]