Name = "Soup.Build.Extensions"
Language = "C#"
Version = "0.1.7"
Source = [
	"BuildOperation.cs",
	"IBuildStateExtensions.cs",
	"IValueExtensions.cs",
	"IValueListExtensions.cs",
	"IValueTableExtensions.cs",
	"PackageReference.cs",
	"SharedOperations.cs",
]

[Dependencies]
Runtime = [
	{ Reference = "Opal@1.0.1" },
	{ Reference = "Soup.Build@0.1.3", ExcludeRuntime = true },
]