Name = "Soup.Build.Extensions"
Language = "C#|0.1.0"
Version = "0.2.0"
Source = [
	"BuildOperation.cs",
	"IBuildStateExtensions.cs",
	"IValueExtensions.cs",
	"IValueListExtensions.cs",
	"IValueTableExtensions.cs",
]

[Dependencies]
Runtime = [
	{ Reference = "Opal@1.0.2" },
	{ Reference = "Soup.Build@0.1.4", ExcludeRuntime = true },
]