Name = "Soup.Cpp.UnitTests"
Language = "C++"
Version = "1.0.0"
Type = "Executable"
Dependencies = [
	"json11@1.0.1",
	"../../../../Dependencies/SoupTest/Assert/",
	"../../../Build/Runtime/",
	"../Extension/",
]
Source = [
	"gen/Main.cpp"
]
IncludePaths = [
	"./"
]