Name = "Soup.Cpp"
Language = "C++"
Type = "DynamicLibrary"
Version = "1.0.0"
Interface = "Source/Module.cpp"
Source = [
	"Source/RegisterBuildExtension.cpp",
]

[Dependencies]
Runtime = [
	"Opal@0.2.1",
	"Soup.Build.Utilities@0.4.2",
	"../Compiler/Core/",
	"../Compiler/Clang/",
	"../Compiler/MSVC/",
]
Build = [
	"../../TestBuild/",
]
Test = [
	"Soup.Test.Assert@0.1.8",
	"../../../Build/TestExtensions/",
]

[Tests]
Source = [
	"UnitTests/gen/Main.cpp"
]
IncludePaths = [
	"UnitTests/",
]
