Name = "Soup.Cpp"
Language = "C++"
Type = "DynamicLibrary"
Version = "1.0.0"
Interface = "Module.cpp"
Source = [
	"RegisterBuildExtension.cpp",
]

[Dependencies]
Runtime = [
	"Opal@0.1.10",
	"../../../Build/Runtime/",
	"../Compiler/Core/",
	"../Compiler/Clang/",
	"../Compiler/MSVC/",
]
Build = [
	# TODO "../../TestBuild/",
]
Test = [
	"Soup.Test.Assert@0.1.8",
	"../../../Build/Runtime/",
]

[Tests]
Source = [
	"../Extension.UnitTests/gen/Main.cpp"
]
IncludePaths = [
	"../Extension.UnitTests/",
]
