Name = "Soup.Cpp"
Language = "C++"
Type = "DynamicLibrary"
Version = "1.0.0"
Dependencies = [
	"Opal@0.1.6",
	"../../../Build/Runtime/",
	"../Compiler/Core/",
	"../Compiler/Clang/",
	"../Compiler/MSVC/",
]

Interface = "Module.cpp"
Source = [
	"RegisterBuildExtension.cpp",
]
PlatformLibraries = [
	"shell32.lib",
]
