Name = "Soup.Test"
Language = "C++"
Type = "DynamicLibrary"
Version = "0.1.1"
Source = [
	"RegisterBuildExtension.cpp",
]

[Dependencies]
Runtime = [
	"Opal@0.1.10",
	"../Cpp/Compiler/Core/",
	# "Soup.Build.Compiler@0.3.0",
	"../Cpp/Compiler/Clang/",
	# "Soup.Build.Compiler.Clang@0.3.0",
	"../Cpp/Compiler/MSVC/",
	# "Soup.Build.Compiler.MSVC@0.3.0",
]