Name = "Soup.Test"
Type = "DynamicLibrary"
Version = "0.1.1"

Dependencies = [
	"Opal@0.1.5",
	"../Compiler/Core/",
	# "Soup.Build.Compiler@0.3.0",
	"../Compiler/Clang/",
	# "Soup.Build.Compiler.Clang@0.3.0",
	"../Compiler/MSVC/",
	# "Soup.Build.Compiler.MSVC@0.3.0",
]

Source = [
	"RegisterBuildExtension.cpp",
]
