Name = "Soup.Test"
Type = "DynamicLibrary"
Version = "1.0.0"

Dependencies = [
	# "../../Dependencies/Opal/Source/",
	"Opal@0.1.1",
	"../../Build/Runtime/",
	"../Compiler/Core/",
	"../Compiler/Clang/",
	"../Compiler/MSVC/",
]

Source = [
	"RegisterBuildExtension.cpp",
]
