Name = "Samples.SimpleBuildExtension.Extension"
Language = "C#"
Version = "1.0.0"
Source = [
	"CustomBuildTask.cs"
]

[Dependencies]
Runtime = [
	{ Reference = "Soup.Build@0.1.3", ExcludeRuntime = true },
	{ Reference = "Soup.Build.Extensions@0.1.8" },
	{ Reference = "Opal@1.0.1" },
]