Name = "Soup.CSharp.Compiler.Core.UnitTests"
Version = "1.0.0"
Type = "Executable"
Dependencies = [
	"../Core/",
	"../../../../Build/Runtime/",
	"../../../../TestUtilities/",
	"Soup.Test.Assert@0.1.6",
]
Source = [
	"gen/Main.cpp"
]
IncludePaths = [
	"./",
]
PlatformLibraries = [
	"shell32.lib",
]
