Name = "SoupEngineWrapper"
Version = "1.0.0"
Dependencies = [
	# "../../../Dependencies/Opal/Source/",
  "../Definition/",
	"Opal@0.1.1",
]

Public = "Module.cpp"
Source = [
  "GraphNodeListWrapper.cpp",
  "ValueWrapper.cpp",
]
