[Projects]
"C++" = [
	{ Name = "Samples.SimpleBuildExtension.Executable", Version = "C:/Users/mwasp/source/repos/Soup/Samples/Cpp/BuildExtension/Executable" },
]
"C#" = [
	{ Name = "Samples.Cpp.BuildExtension.Extension", Version = "C:/Users/mwasp/source/repos/Soup/Samples/Cpp/BuildExtension/Extension/" },
	{ Name = "Soup.Build", Version = "Soup.Build@0.1.3" },
	{ Name = "Soup.Build.Extensions", Version = "Soup.Build.Extensions@0.2.0" },
	{ Name = "Opal", Version = "Opal@1.0.3" },
]
