Name = "Soup"
Version = "0.6.0"
Type = "Executable"

# Ensure the core build extensions are runtime dependencies
Dependencies = [
	"../Core/",
	"../RecipeBuildExtension/",
]

Source = [
	"Main.cpp",
]
IncludePaths = [
	"Commands/",
	"Options/",
]
