Name = "Soup.Core"
Language = "C++"
Version = "0.1.0"

Dependencies = [
	"../../../Dependencies/LzmaSdk/CPP/Library/",
	"json11@1.0.1",
	"toml11@1.0.1",
	"../OpalExtensions/",
	"../../Build/Contracts/",
	# "Soup.Build@0.3.0",
	"../../Build/Utilities/",
	# "Soup.Build.Utilities@0.3.0",
	"../../Build/Runtime/",
]
Defines = [
	# "LOCAL_DEBUG",
]
Interface = "Source/Module.cpp"
IncludePaths = [
	"Source/",
	"Source/Compiler/",
	"Source/Utils/",
]

DevDependencies = [
	"../../Extensions/TestBuild/",
	"Soup.Test.Assert@0.1.7",
]

	[Tests]
	Source = [
		"UnitTests/gen/Main.cpp"
	]
	IncludePaths = [
		"UnitTests/",
	]
	PlatformLibraries = [
		"OleAut32.lib",
		"shell32.lib",
		"User32.lib",
	]