Name = "Soup.Core"
Language = "C++|0.1"
Version = "0.1.1"
Defines = [
	# "LOCAL_DEBUG",
	# "TRACE_SYSTEM_ACCESS",
]
IncludePaths = [
	"Source/",
]
Interface = "Source/Module.cpp"
Source = [
	"Source/Recipe/LanguageReferenceParser.cpp",
	"Source/SML/SMLParser.cpp",
	"Source/ValueTable/Value.cpp",
]

[Dependencies]
Build = [
	"Soup.Test.Cpp@0.2.1",
]
Runtime = [
	"json11@1.0.2",
	"Opal@0.4.1",
	"toml11@1.0.2",
	"../../../../RE-Flex/",
	"../../Monitor/Host/",
	"CryptoPP@1.0.2",
]
Test = [
	"Soup.Test.Assert@0.2.1",
]

[Tests]
Source = [
	"UnitTests/gen/Main.cpp"
]
IncludePaths = [
	"UnitTests/",
]