Name = "Soup.Core"
Language = "C++"
Version = "0.1.0"

Dependencies = [
	"../../../Dependencies/LzmaSdk/CPP/Library/",
	"json11@1.0.1",
	"toml11@1.0.1",
	"../OpalExtensions/",
	"../../Build/Contracts/",
	# "Soup.Build@0.3.0",
	"../../Build/Utilities/",
	# "Soup.Build.Utilities@0.3.0",
	"../../Build/Runtime/",
]
Defines = [
	# "LOCAL_DEBUG",
]
Interface = "Module.cpp"
IncludePaths = [
	"./",
	"Compiler/",
	"Utils/",
]

DevDependencies = [
	# "../../Extensions/TestBuild/",
	"Soup.Test.Assert@0.1.7",
	"../../TestUtilities/",
]

	[Tests]
	Source = [
		"../Core.UnitTests/gen/Main.cpp"
	]
	IncludePaths = [
		"../Core.UnitTests/",
	]