Name = "Soup.Core"
Language = "C++"
Version = "0.1.1"
Defines = [
	# "LOCAL_DEBUG",
	# "TRACE_SYSTEM_ACCESS",
]
IncludePaths = [
	"Source/",
]
Interface = "Source/Module.cpp"
Source = [
	"Source/ValueTable/Value.cpp",
]

[Dependencies]
Build = [
	# "Soup.Test.Cpp@0.1.3",
]
Runtime = [
	"json11@1.0.1",
	"Opal@0.3.0",
	"toml11@1.0.1",
	"../../Monitor/Host/",
	"CryptoPP@1.0.1",
]
Test = [
	"Soup.Test.Assert@0.1.8",
]

[Tests]
Source = [
	"UnitTests/gen/Main.cpp"
]
IncludePaths = [
	"UnitTests/",
]