Name = "Soup.Core"
Version = "0.1.0"

Dependencies = [
	"../../../Dependencies/LzmaSdk/CPP/Library/",
	"json11@1.0.0",
	"toml11@1.0.0",
	"../OpalExtensions/",
	"../../Build/Contracts/",
	# "Soup.Build@0.3.0",
	"../../Build/Utilities/",
	# "Soup.Build.Utilities@0.3.0",
	"../../Build/Execute/",
	"../../Build/Evaluate/",
]
Defines = [
	# "LOCAL_DEBUG",
]
Public = "Module.cpp"
IncludePaths = [
	"./",
	"Compiler/",
	"Utils/",
]

DevDependencies = [
	"../../Extensions/TestBuild/",
	"Soup.Test.Assert@0.1.5",
	"../../TestUtilities/",
]

	[Tests]
	Source = [
		"../Core.UnitTests/gen/Main.cpp"
	]
	IncludePaths = [
		"../Core.UnitTests/",
	]