Name = "Soup.Core"
Language = "C++"
Version = "0.1.1"
Defines = [
	# "LOCAL_DEBUG",
]
Interface = "Source/Module.cpp"
IncludePaths = [
	"Source/",
	"Source/Compiler/",
	"Source/Utils/",
]

[Dependencies]
Runtime = [
	"Soup.Build@0.4.2",
	"Soup.Build.Utilities@0.4.2",
	"../../Build/Runtime/",
]
Build = [
	# TODO: "../../Extensions/TestBuild/",
]
Test = [
	"Soup.Test.Assert@0.1.8",
]

[Tests]
Source = [
	"UnitTests/gen/Main.cpp"
]
IncludePaths = [
	"UnitTests/",
]