Name = "Soup.Core"
Language = "C++"
Version = "0.1.1"
Defines = [
	# "LOCAL_DEBUG",
	# "TRACE_SYSTEM_ACCESS",
]
IncludePaths = [
	"Source/",
	"../../../Dependencies/OpenSSL/include/",
]
Interface = "Source/Module.cpp"
Source = [
	"Source/ValueTable/Value.cpp",
]

LinkLibraries = [
	# Link against the dynamic libraries
	"../../../Dependencies/OpenSSL/libcrypto.lib",
	"../../../Dependencies/OpenSSL/libssl.lib",
]
RuntimeDependencies = [
	# Copy the dynamic libraries
	"../../../Dependencies/OpenSSL/libcrypto-3-x64.dll",
	"../../../Dependencies/OpenSSL/libssl-3-x64.dll",
]

[Dependencies]
Build = [
	# "Soup.Test.Cpp@0.1.3",
]
Runtime = [
	"json11@1.0.1",
	"Opal@0.3.0",
	"toml11@1.0.1",
	"../../Monitor/Host/",
]
Test = [
	"Soup.Test.Assert@0.1.8",
]

[Tests]
Source = [
	"UnitTests/gen/Main.cpp"
]
IncludePaths = [
	"UnitTests/",
]