[Projects]
"C++" = [
	{ Name = "Soup", Version = "./" },
	{ Name = "Soup.Core", Version = "../Core/" },
	{ Name = "json11", Version = "json11@1.0.1" },
	{ Name = "Opal", Version = "Opal@0.3.0" },
	{ Name = "toml11", Version = "toml11@1.0.1" },
	{ Name = "Monitor.Host", Version = "../../Monitor/Host/" },
	{ Name = "Detours", Version = "Detours@4.0.1" },
	{ Name = "Monitor.Shared", Version = "../../../Monitor/Shared/" },
	{ Name = "CryptoPP", Version = "CryptoPP@1.0.1" },
	{ Name = "Soup.Test.Assert", Version = "Soup.Test.Assert@0.1.8" },
	{ Name = "copy", Version = "../../Tools/Copy/" },
	{ Name = "mkdir", Version = "../../Tools/Mkdir/" },
]
"C#" = [
	{ Name = "Soup.Test.Cpp", Version = "Soup.Test.Cpp@0.2.0" },
	{ Name = "Opal", Version = "Opal@1.0.1" },
	{ Name = "Soup.Build", Version = "Soup.Build@0.1.3" },
	{ Name = "Soup.Build.Extensions", Version = "Soup.Build.Extensions@0.1.7" },
	{ Name = "Soup.Cpp.Compiler", Version = "Soup.Cpp.Compiler@0.2.0" },
	{ Name = "Soup.Cpp.Compiler.MSVC", Version = "Soup.Cpp.Compiler.MSVC@0.2.0" },
	{ Name = "Soup.Cpp", Version = "Soup.Cpp@0.1.0" },
	{ Name = "Soup.CSharp", Version = "Soup.CSharp@0.3.1" },
	{ Name = "Soup.CSharp.Compiler", Version = "Soup.CSharp.Compiler@0.2.0" },
	{ Name = "Soup.CSharp.Compiler.Roslyn", Version = "Soup.CSharp.Compiler.Roslyn@0.1.6" },
]
