Version = 2
[Closures]
[Closures.Root]
"C++" = [
	{ Name = "Soup", Version = "../CLI", Build = "Build0" },
	{ Name = "Soup.Core", Version = "../Core/", Build = "Build0" },
	{ Name = "json11", Version = "1.0.1", Build = "Build1" },
	{ Name = "Opal", Version = "0.4.0", Build = "Build2" },
	{ Name = "toml11", Version = "1.0.1", Build = "Build1" },
	{ Name = "Monitor.Host", Version = "../../Monitor/Host/", Build = "Build0" },
	{ Name = "Detours", Version = "4.0.1", Build = "Build1" },
	{ Name = "Monitor.Shared", Version = "../../Monitor/Shared/", Build = "Build0" },
	{ Name = "CryptoPP", Version = "1.0.1", Build = "Build1" },
	{ Name = "Soup.Test.Assert", Version = "0.1.8", Build = "Build1" },
	{ Name = "copy", Version = "../../Tools/Copy/", Build = "Build0" },
	{ Name = "mkdir", Version = "../../Tools/Mkdir/", Build = "Build0" },
]
"C#" = [
	{ Name = "Soup.Cpp", Version = "0.2.1", Build = "Build3" },
	{ Name = "Opal", Version = "1.0.3", Build = "Build4" },
	{ Name = "Soup.Build", Version = "0.1.3", Build = "Build3" },
	{ Name = "Soup.Build.Extensions", Version = "0.2.0", Build = "Build4" },
	{ Name = "Soup.Build.Extensions.Utilities", Version = "0.2.0", Build = "Build3" },
	{ Name = "Soup.Cpp.Compiler", Version = "0.3.0", Build = "Build3" },
	{ Name = "Soup.Cpp.Compiler.MSVC", Version = "0.3.0", Build = "Build3" },
	{ Name = "Soup.CSharp", Version = "0.5.0", Build = "Build3" },
	{ Name = "Soup.CSharp.Compiler", Version = "0.4.0", Build = "Build3" },
	{ Name = "Soup.CSharp.Compiler.Roslyn", Version = "0.4.0", Build = "Build3" },
]
[Closures.Build0]
"C#" = [
	{ Name = "C++", Version = "0.1." },
]
[Closures.Build1]
"C#" = [
	{ Name = "C++", Version = "0.." },
]
[Closures.Build2]
"C#" = [
	{ Name = "C++", Version = "0.1.0" },
]
[Closures.Build3]
"C#" = [
	{ Name = "C#", Version = "0.." },
]
[Closures.Build4]
"C#" = [
	{ Name = "C#", Version = "0.1.0" },
]
