Version = 1
[Projects]
"C++" = [
	{ Name = "Soup", Version = "../CLI" },
	{ Name = "Soup.Core", Version = "../Core/" },
	{ Name = "json11", Version = "1.0.1" },
	{ Name = "Opal", Version = "0.3.0" },
	{ Name = "toml11", Version = "1.0.1" },
	{ Name = "Monitor.Host", Version = "../../Monitor/Host/" },
	{ Name = "Detours", Version = "4.0.1" },
	{ Name = "Monitor.Shared", Version = "../../Monitor/Shared/" },
	{ Name = "CryptoPP", Version = "1.0.1" },
	{ Name = "Soup.Test.Assert", Version = "0.1.8" },
	{ Name = "copy", Version = "../../Tools/Copy/" },
	{ Name = "mkdir", Version = "../../Tools/Mkdir/" },
]
"C#" = [
	{ Name = "Soup.Cpp", Version = "0.1.0" },
	{ Name = "Opal", Version = "1.0.1" },
	{ Name = "Soup.Build", Version = "0.1.3" },
	{ Name = "Soup.Build.Extensions", Version = "0.1.8" },
	{ Name = "Soup.Cpp.Compiler", Version = "0.2.0" },
	{ Name = "Soup.Cpp.Compiler.MSVC", Version = "0.2.0" },
	{ Name = "Soup.CSharp", Version = "0.3.1" },
	{ Name = "Soup.CSharp.Compiler", Version = "0.3.1" },
	{ Name = "Soup.CSharp.Compiler.Roslyn", Version = "0.3.1" },
]
