[Projects]
"C++" = [
	{ Name = "Soup", Version = "./" },
	{ Name = "Soup.Core", Version = "../Core/" },
	{ Name = "json11", Version = "json11@1.0.1" },
	{ Name = "Opal", Version = "Opal@0.3.0" },
	{ Name = "toml11", Version = "toml11@1.0.1" },
	{ Name = "Monitor.Host", Version = "../../Monitor/Host/" },
	{ Name = "Detours", Version = "../../../Dependencies/Detours/src/" },
	{ Name = "Monitor.Shared", Version = "../../../Monitor/Shared/" },
	{ Name = "Soup.Test.Assert", Version = "Soup.Test.Assert@0.1.8" },
	{ Name = "copy", Version = "../../Tools/Copy/" },
	{ Name = "mkdir", Version = "../../Tools/Mkdir/" },
]
"C#" = [
	{ Name = "Soup.Test.Cpp", Version = "Soup.Test.Cpp@0.1.3" },
	{ Name = "Opal", Version = "Opal@1.0.1" },
	{ Name = "Soup.Build", Version = "../../GenerateSharp/Build/" },
	{ Name = "Soup.Build.Extensions", Version = "../../GenerateSharp/Build.Extensions/" },
	{ Name = "Soup.Cpp.Compiler", Version = "../../GenerateSharp/Extensions/Cpp/Compiler/Core/" },
	{ Name = "Soup.Cpp.Compiler.MSVC", Version = "../../GenerateSharp/Extensions/Cpp/Compiler/MSVC/" },
]
