Name = "Soup"
Version = "0.7.0"
Type = "Executable"

# Ensure the core build extensions are runtime dependencies
Dependencies = [
	"../Core/",
	"../../Extensions/RecipeBuild/",
]
RuntimeDependencies = [
	"LocalUserConfig.json",
]
Source = [
	"Main.cpp",
]
IncludePaths = [
	"Commands/",
	"Options/",
]
