Name = "Soup"
Language = "C++"
Version = "0.9.5"
Type = "Executable"

# Ensure the core build extensions are runtime dependencies
Dependencies = [
	"../Core/",
	"../../Tools/Copy/",
	"../../Tools/Mkdir/",
	"../../Extensions/Cpp/Extension/",
	"../../Extensions/CSharp/Extension/",
	"../../Monitor/Shared/",
]
RuntimeDependencies = [
	"LocalUserConfig.json",
]
Source = [
	"Source/Main.cpp",
]
IncludePaths = [
	"Source/Commands/",
	"Source/Options/",
]
PlatformLibraries = [
	"OleAut32.lib",
	"shell32.lib",
	"User32.lib",
]

DevDependencies = [
	# TODO: "../../Extensions/TestBuild/",
	"Soup.Test.Assert@0.1.7",
]

	[Tests]
	Source = [
		"UnitTests/gen/Main.cpp"
	]
	IncludePaths = [
		"UnitTests/",
	]
	PlatformLibraries = [
		"OleAut32.lib",
		"shell32.lib",
		"User32.lib",
	]
