Name = "Soup"
Version = "0.8.11"
Type = "Executable"

# Ensure the core build extensions are runtime dependencies
Dependencies = [
	"../Core/",
	"../../Tools/Copy/",
	"../../Tools/Mkdir/",
	"../../Extensions/Cpp/Extension/",
	"../../Extensions/CSharp/Extension/",
	"../../Monitor/Shared/",
]
RuntimeDependencies = [
	"LocalUserConfig.json",
]
Source = [
	"Main.cpp",
]
IncludePaths = [
	"Commands/",
	"Options/",
]
PlatformLibraries = [
	"OleAut32.lib",
	"shell32.lib",
	"User32.lib",
]

