Name = "Soup"
Version = "0.8.2"
Type = "Executable"

# Ensure the core build extensions are runtime dependencies
Dependencies = [
	"../Core/",
	"../../Extensions/RecipeBuild/",
	"../../Monitor/Shared/",
]
RuntimeDependencies = [
	"LocalUserConfig.json",
]
Source = [
	"Main.cpp",
]
IncludePaths = [
	"Commands/",
	"Options/",
]
