Name = "Soup"
Language = "C++"
Version = "0.18.1"
Type = "Executable"

Source = [
	"Source/Main.cpp",
]
IncludePaths = [
	"Source/Commands/",
	"Source/Options/",
]

[Dependencies]
# Ensure the core build extensions are runtime dependencies
Runtime = [
	"../Core/",
	# "../../Build/Generate/",
	"../../Tools/Copy/",
	"../../Tools/Mkdir/",
	#"C#|Soup.Cpp@0.1.0",
	#"C#|Soup.CSharp@0.1.0",
	"../../Monitor/Host/",
]
Build = [
	# TODO: "Soup.Test.Cpp@0.1.3",
]
Test = [
	"Soup.Test.Assert@0.1.8",
]

[Tests]
Source = [
	"UnitTests/gen/Main.cpp"
]
IncludePaths = [
	"UnitTests/",
]
