Name = "Soup"
Language = "C++"
Version = "0.13.0"
Type = "Executable"

Source = [
	"Source/Main.cpp",
]
IncludePaths = [
	"Source/Commands/",
	"Source/Options/",
]

[Dependencies]
# Ensure the core build extensions are runtime dependencies
Runtime = [
	"../Core/",
	# "../../Build/Generate/",
	"../../Tools/Copy/",
	"../../Tools/Mkdir/",
	# "../../Extensions/Cpp/Extension/",
	# "../../Extensions/CSharp/Extension/",
	"../../Monitor/Host/",
]
Build = [
	# TODO: "Soup.Test.Cpp@0.1.1",
]
Test = [
	"Soup.Test.Assert@0.1.8",
]

[Tests]
Source = [
	"UnitTests/gen/Main.cpp"
]
IncludePaths = [
	"UnitTests/",
]
