Name = "Soup"
Version = "0.6.2"
Type = "Executable"

# Ensure the core build extensions are runtime dependencies
Dependencies = [
  "../Core/",
  "../../Extensions/RecipeBuild/",
]

Source = [
  "Main.cpp",
]
IncludePaths = [
  "Commands/",
  "Options/",
]
