Name = "Soup"
Version = "0.8.10"
Type = "Executable"

# Ensure the core build extensions are runtime dependencies
Dependencies = [
	"../Core/",
	"../../Tools/Copy/",
	"../../Tools/Mkdir/",
	"../../Extensions/RecipeBuild/",
	"../../Monitor/Shared/",
]
RuntimeDependencies = [
	"LocalUserConfig.json",
]
Source = [
	"Main.cpp",
]
IncludePaths = [
	"Commands/",
	"Options/",
]
