Name = "Soup.CSharp"
Type = "DynamicLibrary"
Version = "1.0.0"
Dependencies = [
	"Opal@0.1.5",
	"../Compiler/Core/",
]

Public = "Module.cpp"
Source = [
	"RegisterBuildExtension.cpp",
]
PlatformLibraries = [
	"shell32.lib",
]
