Name = "Soup.CSharp"
Language = "C++"
Type = "DynamicLibrary"
Version = "1.0.0"
Interface = "Module.cpp"
Source = [
	"RegisterBuildExtension.cpp",
]

[Dependencies]
Runtime = [
	"Opal@0.2.1",
	"../Compiler/Core/",
]
Build = [
	# TODO "../../TestBuild/",
]
Test = [
	"Soup.Test.Assert@0.1.8",
	"../../../Build/Runtime/",
]

[Tests]
Source = [
	"../Extension.UnitTests/gen/Main.cpp",
]
IncludePaths = [
	"../Extension.UnitTests/",
]