Name = "Soup.CSharp"
Language = "C++"
Type = "DynamicLibrary"
Version = "1.0.0"
Dependencies = [
	"Opal@0.1.6",
	"../Compiler/Core/",
]

Interface = "Module.cpp"
Source = [
	"RegisterBuildExtension.cpp",
]
PlatformLibraries = [
	"shell32.lib",
]
