Name = "SoupCompilerCoreUnitTests"
Version = "1.0.0"
Type = "Executable"
Dependencies = [
	"../Core/",
	"../../../Build/Evaluate/",
	"../../../TestUtilities/",
	"SoupTest@0.1.0",
]
Source = [
	"gen/Main.cpp"
]
IncludePaths = [
	"./",
]
