Name = "SoupEngineCore"
Version = "0.1.0"

Dependencies = [
	"../../Opal/",
	"../Definition/",
	"../Wrapper/",
]

Public = "Module.cpp"
Source = [
	"BuildGraphNodeList.cpp",
	"Value.cpp",
]
