Name = "SoupEngineCore"
Version = "0.1.0"

Dependencies = [
	# "../../../Dependencies/Opal/Source/",
	"../Definition/",
	"../Wrapper/",
	"Opal@0.1.1",
]

Public = "Module.cpp"
Source = [
	"BuildGraphNodeList.cpp",
	"Value.cpp",
]
