Name = "SoupCoreUnitTests"
Version = "1.0.0"
Type = "Executable"
Dependencies = [
	"json11@1.0.0",
	# "../../Dependencies/SoupTest/Assert/",
	"SoupTest@0.1.0",
	"../Core/",
	"../../TestUtilities/",
]
Source = [
	"gen/Main.cpp"
]
IncludePaths = [
	"./",
]
