Name = "SoupCoreUnitTests"
Version = "1.0.0"
Type = "Executable"
Dependencies = [
  # "../../Dependencies/json11/",
  # "../../Dependencies/SoupTest/Assert/",
  "../Core/",
  "../TestUtilities/",
	"json11@1.0.0",
	"SoupTest@0.1.0",
]
Source = [
  "gen/Main.cpp"
]
IncludePaths = [
  "./",
]
