Name = "Soup.Core.UnitTests"
Version = "1.0.0"
Type = "Executable"
Dependencies = [
	"json11@1.0.0",
	"Soup.Test.Assert@0.1.6",
	"../Core/",
	"../../TestUtilities/",
]
Source = [
	"gen/Main.cpp"
]
IncludePaths = [
	"./",
]
PlatformLibraries = [
	"OleAut32.lib",
	"shell32.lib",
	"User32.lib",
]
