Name = "SoupCompilerMSVCUnitTests"
Version = "1.0.0"
Type = "Executable"
Dependencies = [
	"../../../Dependencies/SoupTest/Assert/",
	"../MSVC/",
	"../../TestUtilities/",
]
Source = [
	"gen/Main.cpp",
]
IncludePaths = [
	"./",
]
