Name = "Soup.Compiler.MSVC.UnitTests"
Version = "1.0.0"
Type = "Executable"
Dependencies = [
	"../MSVC/",
	"../../../TestUtilities/",
	"../../../Build/Generate/",
	"Soup.Test.Assert@0.1.6",
]
Source = [
	"gen/Main.cpp",
]
IncludePaths = [
	"./",
]
PlatformLibraries = [
	"shell32.lib",
]
