Name = "SoupCompilerMSVCUnitTests"
Version = "1.0.0"
Type = "Executable"
Dependencies = [
	"../MSVC/",
	"../../../TestUtilities/",
	"../../../Build/Evaluate/",
	"Soup.Test.Assert@0.1.6",
]
Source = [
	"gen/Main.cpp",
]
IncludePaths = [
	"./",
]
