Name = "SoupCompilerMSVCUnitTests"
Version = "1.0.0"
Type = "Executable"
Dependencies = [
	# "../../../Dependencies/SoupTest/Assert/",
	"../MSVC/",
	"../../../TestUtilities/",
	"../../../Build/Runtime/",
	"SoupTest@0.1.0",
]
Source = [
	"gen/Main.cpp",
]
IncludePaths = [
	"./",
]
