[Projects]
"C#" = [
	{ Name = "Soup.Cpp", Version = "./" },
	{ Name = "Opal", Version = "Opal@1.0.1" },
	{ Name = "Soup.Build", Version = "../../../Build/" },
	{ Name = "Soup.Build.Extensions", Version = "../../../Build.Extensions/" },
	{ Name = "Soup.Cpp.Compiler", Version = "../Compiler/Core/" },
	{ Name = "Soup.Cpp.Compiler.MSVC", Version = "../Compiler/MSVC/" },
]
