Name = "SoupCompilerCore"
Version = "0.1.0"
Dependencies = [
	"../../../../Dependencies/Opal/Source/",
	# "Opal@0.1.2",
	"../../../Build/Utilities/",
	# "Soup.Build.Utilities@0.3.0",
]

Public = "Module.cpp"
