Name = "SoupCompilerCore"
Version = "0.1.0"
Dependencies = [
	"../../../Tools/Copy/",
	"../../../Tools/Mkdir/",
	"Opal@0.1.3",
	"../../../Build/Utilities/",
	# "Soup.Build.Utilities@0.3.0",
]

Public = "Module.cpp"
