Name = "SoupCompiler"
Version = "0.1.0"
Dependencies = [
  # "../../../Dependencies/Opal/Source/",
  "Opal@0.1.1",
  "../../../Build/Extensions/",
  # "Soup.Build.Extensions@0.2.0",
]

Public = "Module.cpp"
