Name = "Soup.Build.Runtime"
Language = "C#"
Version = "1.0.0"
Source = [
	"Contracts/BuildState.cs",
	"Contracts/ValueList.cs",
	"Contracts/ValueTable.cs",
	"OperationGraph/OperationGraph.cs",
	"OperationGraph/OperationGraphGenerator.cs",
	"OperationGraph/OperationInfo.cs",
	"FileSystemState.cs",
]

[Dependencies]
Runtime = [
	"../Contracts/",
	"../Opal/",
]