Name = "Monitor.Detours"
Language = "C++"
Version = "1.0.0"
Type = "DynamicLibrary"
Dependencies = [
	"../../../Dependencies/Detours/src/",
	"../Shared/",
]
Defines = [
	# "ENABLE_MONITOR_DEBUG",
	# "TRACE_DETOUR_CLIENT",
]
Interface = "Module.cpp"
PlatformLibraries = [
	"Advapi32.lib",
	"shell32.lib",
]
