Name = "Opal.Extensions"
Version = "0.1.0"
Public = "Module.cpp"
Dependencies = [
	"../../../Dependencies/cpp-httplib/",
	# "httplib@1.0.0",
	"Opal@0.1.4",
]
Defines = [
	# "ENABLE_FIDDLER_PROXY",
]