Name = "Soup.RecipeBuild"
Type = "DynamicLibrary"
Version = "1.0.0"
Dependencies = [
	"Opal@0.1.5",
	"../../Build/Runtime/",
	"../Compiler/Core/",
	"../Compiler/Clang/",
	"../Compiler/MSVC/",
]

Public = "Module.cpp"
Source = [
	"RegisterBuildExtension.cpp",
]
PlatformLibraries = [
	"shell32.lib",
]
