Name = "Soup.Build.Generate"
Language = "C#"
Version = "1.0.0"
Type = "Executable"
Source = [
	"Contracts/ValueTableManager.cs",
	"Contracts/ValueTableReader.cs",
	"Contracts/ValueTableWriter.cs",
	"OperationGraph/OperationGraphManager.cs",
	"OperationGraph/OperationGraphReader.cs",
	"OperationGraph/OperationGraphWriter.cs",
	"Recipe/Recipe.cs",
	"Recipe/RecipeExtensions.cs",
	"Recipe/RecipeToml.cs",
	"BuildConstants.cs",
	"BuildGenerateEngine.cs",
	"BuildTaskManager.cs",
	"ExtensionLoadContext.cs",
	"Program.cs",
]
NuGetPackages = [
	"Microsoft.Extensions.DependencyInjection@5.0.1"
]

[Dependencies]
Runtime = [
	"../Contracts/",
	"../Opal/",
	"../Runtime/",
	"../Utilities/",
	"../../../../Tomlyn/src/Tomlyn/",
]