Name = "SoupTestUtilities"
Version = "0.1.0"
Dependencies = [
	# "../../Dependencies/SoupTest/Assert/",
	"SoupTest@0.1.0",
	"../../Dependencies/Opal/Source/",
	# "Opal@0.1.2",
	"../Build/Utilities/",
]
Public = "Module.cpp"
