Name = "SoupTestUtilities"
Version = "0.1.0"
Dependencies = [
  # "../../Dependencies/SoupTest/Assert/",
	# "../../Dependencies/Opal/Source/",
  "../Engine/Core/",
  "../Core/",
  "SoupTest@0.1.0",
	"Opal@0.1.1",
]
Public = "Module.cpp"
