Name = "SoupCompilerClangUnitTests"
Version = "1.0.0"
Type = "Executable"
Dependencies = [
  # "../../../Dependencies/SoupTest/Assert/",
  "../Clang/",
  "../../../TestUtilities/",
  "SoupTest@0.1.0",
]

Source = [
  "gen/Main.cpp",
]
IncludePaths = [
  "./",
]
