Name = "SoupCompilerClangUnitTests"
Version = "1.0.0"
Type = "Executable"
Dependencies = [
	"../Clang/",
	"../../../Build/Evaluate/",
	"../../../TestUtilities/",
	"Soup.Test.Assert@0.1.5",
]

Source = [
	"gen/Main.cpp",
]
IncludePaths = [
	"./",
]
