name: CI

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Soup
      uses: SoupBuild/Setup-Soup@v1
      with:
        version: v0.6.3-alpha
    - name: Run a one-line script
      run: dir
    - name: Decompress
      uses: TonyBogdanov/zip@1.0
      with:
        args: unzip -qq ./starging/soup.zip -d ./bin
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
