name: CI
on: 
  pull_request:
    branches: [ main ]
jobs:
  windows-build:
    strategy:
      matrix:
        os: [ windows-2022, ubuntu-22.04 ]
        config: [ Debug, Release ]
    name: PR Build ${{matrix.os}} ${{matrix.config}}
    runs-on: ${{ matrix.os }}
    steps:
    # Setup Environment
    - uses: actions/checkout@v2
      with:
        path: "Soup"
        submodules: true
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Setup Soup Build
      uses: soupbuild/setup-soup@v1
      with:
        version: latest

    # Build Soup
    - name: Soup Where
      run: swhere
    - name: Soup Restore Client
      run: soup restore ./Soup/Source/Client/CLI/ -v:d
    - name: Soup Build Client
      if: matrix.os != 'ubuntu-22.04'
      run: soup build ./Soup/Source/Client/CLI/ -v:d -flavor ${{matrix.config}}
    - name: Soup Run Version
      if: matrix.os != 'ubuntu-22.04'
      run: soup run ./Soup/Source/Client/CLI/ -v:d -flavor ${{matrix.config}} -args version
    - name: Soup Restore GenerateTest
      run: soup restore ./Soup/Source/GenerateTest/
    - name: Soup Build GenerateTest
      if: matrix.os != 'ubuntu-22.04'
      run: soup build ./Soup/Source/GenerateTest/ -flavor ${{matrix.config}} -v:d
    # - name: Soup Restore SWhere
    #   run: soup restore ./Soup/Source/GenerateSharp/Swhere/
    # - name: Soup Build SWhere
    #   run: soup build ./Soup/Source/GenerateSharp/Swhere/ -flavor ${{matrix.config}} -v:d
    # - name: Soup Restore PackageManager
    #   run: soup restore ./Soup/Source/GenerateSharp/PackageManager/
    # - name: Soup Build PackageManager
    #   run: soup build ./Soup/Source/GenerateSharp/PackageManager/ -flavor ${{matrix.config}} -v:d
    - name: Soup Restore Tools
      run: soup restore ./Soup/Source/Client/Tools/ -v:d
    - name: Soup Build Tools
      if: matrix.os != 'ubuntu-22.04'
      run: soup build ./Soup/Source/Client/Tools/ -v:d -flavor ${{matrix.config}}

    # Build DotNet
    - name: DotNet Restore
      if: matrix.os != 'ubuntu-22.04'
      run: dotnet restore ./Soup/Source/GenerateSharp/GenerateSharp.sln
    - name: DotNet Build
      if: matrix.os != 'ubuntu-22.04'
      run: dotnet build -c ${{matrix.config}} --no-restore ./Soup/Source/GenerateSharp/GenerateSharp.sln
    - name: DotNet Test
      if: matrix.os != 'ubuntu-22.04'
      run: dotnet test -c ${{matrix.config}} --no-build --verbosity normal ./Soup/Source/GenerateSharp/GenerateSharp.sln

    # Build Tools
    - name: Soup Restore PrintGraph
      run: soup restore ./Soup/Source/Tools/PrintGraph/
    - name: Soup Build PrintGraph
      if: matrix.os != 'ubuntu-22.04'
      run: soup build ./Soup/Source/Tools/PrintGraph/ -flavor ${{matrix.config}} -v:d
    - name: Soup Restore PrintValueTable
      run: soup restore ./Soup/Source/Tools/PrintValueTable/
    - name: Soup Build PrintValueTable
      if: matrix.os != 'ubuntu-22.04'
      run: soup build ./Soup/Source/Tools/PrintValueTable/ -flavor ${{matrix.config}} -v:d

    # Build Samples
    - name: Soup Restore C BuildExtension
      run: soup restore ./Soup/Samples/C/BuildExtension/Executable/
    - name: Soup Build C BuildExtension
      if: matrix.os != 'ubuntu-22.04'
      run: soup build ./Soup/Samples/C/BuildExtension/Executable/ -flavor ${{matrix.config}} -v:d
    - name: Soup Build C ConsoleApplication
      if: matrix.os != 'ubuntu-22.04'
      run: soup build ./Soup/Samples/C/ConsoleApplication/ -flavor ${{matrix.config}} -v:d
    - name: Soup Build C DynamicLibrary
      if: matrix.os != 'ubuntu-22.04'
      run: soup build ./Soup/Samples/C/DynamicLibrary/Application/ -flavor ${{matrix.config}} -v:d
    - name: Soup Build C StaticLibrary
      if: matrix.os != 'ubuntu-22.04'
      run: soup build ./Soup/Samples/C/StaticLibrary/Application/ -flavor ${{matrix.config}} -v:d
    - name: Soup Build C WindowsApplication
      if: matrix.os != 'ubuntu-22.04'
      run: soup build ./Soup/Samples/C/WindowsApplication/ -flavor ${{matrix.config}} -v:d

    - name: Soup Restore Cpp BuildExtension
      run: soup restore ./Soup/Samples/Cpp/BuildExtension/Executable/
    - name: Soup Build Cpp BuildExtension
      run: soup build ./Soup/Samples/Cpp/BuildExtension/Executable/ -flavor ${{matrix.config}} -v:d
    - name: Soup Build Cpp ConsoleApplication
      run: soup build ./Soup/Samples/Cpp/ConsoleApplication/ -flavor ${{matrix.config}} -v:d
    - name: Soup Build Cpp DirectX
      if: matrix.os != 'ubuntu-22.04'
      run: soup build ./Soup/Samples/Cpp/DirectX/ -flavor ${{matrix.config}} -v:d
    - name: Soup Build Cpp DynamicLibrary
      if: matrix.os != 'ubuntu-22.04'
      run: soup build ./Soup/Samples/Cpp/DynamicLibrary/Application/ -flavor ${{matrix.config}} -v:d
    - name: Soup Build Cpp ModuleInterface
      if: matrix.os != 'ubuntu-22.04'
      run: soup build ./Soup/Samples/Cpp/ModuleInterface/ -flavor ${{matrix.config}} -v:d
    - name: Soup Restore Cpp ParseJsonFile
      run: soup restore ./Soup/Samples/Cpp/ParseJsonFile/
    - name: Soup Build Cpp ParseJsonFile
      if: matrix.os != 'ubuntu-22.04'
      run: soup build ./Soup/Samples/Cpp/ParseJsonFile/ -flavor ${{matrix.config}} -v:d
    - name: Soup Build Cpp StaticLibrary
      if: matrix.os != 'ubuntu-22.04'
      run: soup build ./Soup/Samples/Cpp/StaticLibrary/Application/ -flavor ${{matrix.config}} -v:d
    - name: Soup Build Cpp WindowsApplication
      if: matrix.os != 'ubuntu-22.04'
      run: soup build ./Soup/Samples/Cpp/WindowsApplication/ -flavor ${{matrix.config}} -v:d

    # - name: Soup Restore CSharp BuildExtension
    #   run: soup restore ./Soup/Samples/CSharp/BuildExtension/Executable/
    # - name: Soup Build CSharp BuildExtension
    #   run: soup build ./Soup/Samples/CSharp/BuildExtension/Executable/ -flavor ${{matrix.config}} -v:d
    # - name: Soup Build CSharp ConsoleApplication
    #   run: soup build ./Soup/Samples/CSharp/ConsoleApplication/ -flavor ${{matrix.config}} -v:d