name: CI
on: 
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
    # Setup Environment
    - uses: actions/checkout@v2
      with:
        path: "Soup"
        submodules: true
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup Soup Build
      uses: soupbuild/setup-soup@v1
      with:
        version: latest

    # Build DotNet
    - name: DotNet Restore
      run: dotnet restore ./Soup/Source/GenerateSharp/GenerateSharp.sln
    - name: DotNet Build
      run: dotnet build --configuration Release --no-restore ./Soup/Source/GenerateSharp/GenerateSharp.sln
    - name: DotNet Test
      run: dotnet test --no-build --verbosity normal ./Soup/Source/GenerateSharp/GenerateSharp.sln

    # Build Soup
    - name: Soup Install
      run: soup install ./Soup/Source/Client/CLI/ -v:d
    - name: Soup Build
      run: soup build ./Soup/Source/Client/CLI/ -v:d -flavor release
