name: CI

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Download GitHub Release
      uses: i3h/download-release-asset@v1
      with:
        owner: mwasplund
        repo: Soup
        tag: latest
        file: Soup.zip
    - name: Decompress
      uses: TonyBogdanov/zip@1.0
      with:
        args: unzip -qq ./starging/soup.zip -d ./bin
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
