name: CI
on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Setup Soup
      uses: SoupBuild/Setup-Soup@v1
      with:
        version: v0.8.5-alpha
    - name: Soup Install
      run: soup install Source/Client/CLI/ -v:d
    - name: Build Execute UnitTests
      run: soup build Source/Build/Execute.UnitTests/
    - name: Run Execute UnitTests
      run: Source/Build/Execute.UnitTests/out/bin/MSVC/debug/win32/x64/Execute.UnitTests.exe