name: CI
on: 
  pull_request:
    branches: [ main ]
jobs:
  build:
    strategy:
      matrix:
        os: [ windows-2022 ]
        config: [ Debug, Release ]
    name: PR Build ${{matrix.os}} ${{matrix.config}}
    runs-on: ${{ matrix.os }}
    steps:
    # Setup Environment
    - uses: actions/checkout@v2
      with:
        path: "Soup"
        submodules: true
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Setup Soup Build
      uses: soupbuild/setup-soup@v1
      with:
        version: latest

    # Build DotNet
    - name: DotNet Restore
      run: dotnet restore ./Soup/Source/GenerateSharp/GenerateSharp.sln
    - name: DotNet Build
      run: dotnet build -c ${{matrix.config}} --no-restore ./Soup/Source/GenerateSharp/GenerateSharp.sln
    - name: DotNet Test
      run: dotnet test -c ${{matrix.config}} --no-build --verbosity normal ./Soup/Source/GenerateSharp/GenerateSharp.sln

    # Build Soup
    - name: Soup Where
      run: swhere
    - name: Soup Install
      run: soup install ./Soup/Source/Client/CLI/ -v:d
    # TODO: Disabled for openssl - name: Soup Build
    #  run: soup build ./Soup/Source/Client/CLI/ -v:d -flavor ${{matrix.config}}

    # Build Samples
    - name: Soup Build Cpp ModuleConsoleApplication
      run: soup build ./Soup/Samples/Cpp/ModuleConsoleApplication/ -flavor ${{matrix.config}}
    - name: Soup Install Cpp ParseJsonFile
      run: soup install ./Soup/Samples/Cpp/ParseJsonFile/
    - name: Soup Build Cpp ParseJsonFile
      run: soup build ./Soup/Samples/Cpp/ParseJsonFile/ -flavor ${{matrix.config}}
    - name: Soup Install Cpp SimpleBuildExtension
      run: soup install ./Soup/Samples/Cpp/SimpleBuildExtension/Executable/
    - name: Soup Build Cpp SimpleBuildExtension
      run: soup build ./Soup/Samples/Cpp/SimpleBuildExtension/Executable/ -flavor ${{matrix.config}}
    - name: Soup Build Cpp SimpleConsoleApplication
      run: soup build ./Soup/Samples/Cpp/SimpleConsoleApplication/ -flavor ${{matrix.config}}
    - name: Soup Build Cpp StaticLibraryReference
      run: soup build ./Soup/Samples/Cpp/StaticLibraryReference/MyApplication/ -flavor ${{matrix.config}}

    - name: Soup Install CSharp SimpleBuildExtension
      run: soup install ./Soup/Samples/CSharp/SimpleBuildExtension/Executable/
    - name: Soup Build CSharp SimpleBuildExtension
      run: soup build ./Soup/Samples/CSharp/SimpleBuildExtension/Executable/ -flavor ${{matrix.config}}
    - name: Soup Build CSharp SimpleConsoleApplication
      run: soup build ./Soup/Samples/CSharp/SimpleConsoleApplication/ -flavor ${{matrix.config}}
