name: CI
on: 
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
      with:
        path: "Soup"
        submodules: true
    - name: Setup Soup
      uses: SoupBuild/Setup-Soup@v1
      with:
        version: v0.8.5-alpha
    - name: Soup Install
      run: soup install Soup/Source/Client/CLI/ -v:d

    - name: Build Execute UnitTests
      run: soup build Soup/Source/Build/Execute.UnitTests/
    - name: Run Execute UnitTests
      run: soup run Soup/Source/Build/Execute.UnitTests/

    - name: Build Utilities UnitTests
      run: soup build Soup/Source/Build/Utilities.UnitTests/
    - name: Run Utilities UnitTests
      run: soup run Soup/Source/Build/Utilities.UnitTests/

    - name: Build Extensions Compiler Core UnitTests
      run: soup build Soup/Source/Extensions/Compiler/Core.UnitTests/
    - name: Run Extensions Compiler Core UnitTests
      run: soup run Soup/Source/Extensions/Compiler/Core.UnitTests/

    - name: Build Extensions Compiler Clang UnitTests
      run: soup build Soup/Source/Extensions/Compiler/Clang.UnitTests/
    - name: Run Extensions Compiler Clang UnitTests
      run: soup run Soup/Source/Extensions/Compiler/Clang.UnitTests/

    - name: Build Extensions Compiler MSVC UnitTests
      run: soup build Soup/Source/Extensions/Compiler/MSVC.UnitTests/
    - name: Run Extensions Compiler MSVC UnitTests
      run: soup run Soup/Source/Extensions/Compiler/MSVC.UnitTests/

    # openssl not available on CI build
    # - name: Build Client Core UnitTests
    #   run: soup build Soup/Source/Client/Core.UnitTests/
    # - name: Run Client Core UnitTests
    #   run: soup run Soup/Source/Client/Core.UnitTests/
