name: CI
on: 
  pull_request:
    branches: [ main ]
jobs:
  build:
    strategy:
      matrix:
        os: [ windows-2022 ]
        config: [ Debug, Release ]
    name: PR Build ${{matrix.os}} ${{matrix.config}}
    runs-on: ${{ matrix.os }}
    steps:
    # Setup Environment
    - uses: actions/checkout@v2
      with:
        path: "Soup"
        submodules: true
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup Soup Build
      uses: soupbuild/setup-soup@v1
      with:
        version: latest

    # Build DotNet
    - name: DotNet Restore
      run: dotnet restore ./Soup/Source/GenerateSharp/GenerateSharp.sln
    - name: DotNet Build
      run: dotnet build -c ${{matrix.config}} --no-restore ./Soup/Source/GenerateSharp/GenerateSharp.sln
    - name: DotNet Test
      run: dotnet test -c ${{matrix.config}} --no-build --verbosity normal ./Soup/Source/GenerateSharp/GenerateSharp.sln

    # Build Soup
    - name: Soup Where
      run: swhere
    - name: Soup Restore
      run: soup restore ./Soup/Source/Client/CLI/ -v:d
    - name: Soup Build
      run: soup build ./Soup/Source/Client/CLI/ -v:d -flavor ${{matrix.config}}

    # Build Samples
    - name: Soup Restore Cpp BuildExtension
      run: soup restore ./Soup/Samples/Cpp/BuildExtension/Executable/
    - name: Soup Build Cpp BuildExtension
      run: soup build ./Soup/Samples/Cpp/BuildExtension/Executable/ -flavor ${{matrix.config}} -v:d
    - name: Soup Build Cpp ConsoleApplication
      run: soup build ./Soup/Samples/Cpp/ConsoleApplication/ -flavor ${{matrix.config}} -v:d
    - name: Soup Build Cpp DirectX
      run: soup build ./Soup/Samples/Cpp/DirectX/ -flavor ${{matrix.config}} -v:d
    - name: Soup Build Cpp DynamicLibrary
      run: soup build ./Soup/Samples/Cpp/DynamicLibrary/Application/ -flavor ${{matrix.config}} -v:d
    - name: Soup Build Cpp ModuleInterface
      run: soup build ./Soup/Samples/Cpp/ModuleInterface/ -flavor ${{matrix.config}} -v:d
    - name: Soup Restore Cpp ParseJsonFile
      run: soup restore ./Soup/Samples/Cpp/ParseJsonFile/
    - name: Soup Build Cpp ParseJsonFile
      run: soup build ./Soup/Samples/Cpp/ParseJsonFile/ -flavor ${{matrix.config}} -v:d
    - name: Soup Build Cpp StaticLibrary
      run: soup build ./Soup/Samples/Cpp/StaticLibrary/Application/ -flavor ${{matrix.config}} -v:d
    - name: Soup Build Cpp WindowsProject
      run: soup build ./Soup/Samples/Cpp/WindowsProject/ -flavor ${{matrix.config}} -v:d

    - name: Soup Restore CSharp BuildExtension
      run: soup restore ./Soup/Samples/CSharp/BuildExtension/Executable/
    - name: Soup Build CSharp BuildExtension
      run: soup build ./Soup/Samples/CSharp/BuildExtension/Executable/ -flavor ${{matrix.config}} -v:d
    - name: Soup Build CSharp ConsoleApplication
      run: soup build ./Soup/Samples/CSharp/ConsoleApplication/ -flavor ${{matrix.config}} -v:d
