Name = "Samples.CSharp.BuildExtension.Extension"
Language = "C#|0.1.0"
Version = "1.0.0"
Source = [
	"CustomBuildTask.cs"
]

[Dependencies]
Runtime = [
	{ Reference = "Soup.Build@0.1.4", ExcludeRuntime = true },
	{ Reference = "Soup.Build.Extensions@0.2.0" },
	{ Reference = "Opal@1.0.2" },
]